import type {Metadata} from 'next'
import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "@/components/BootstrapClient";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body>
    {children}
    <BootstrapClient></BootstrapClient>
    </body>
    </html>
  )
}
